apiVersion: v1
kind: Service
metadata:
  name: {{ include "spectre-proxy.fullname" . }}
  labels:
    {{- include "spectre-proxy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.metrics.enabled }}
  - port: {{ .Values.metrics.port }}
    targetPort: http
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    {{- include "spectre-proxy.selectorLabels" . | nindent 4 }}
